version: 2
jobs:
  build:
    machine : true
    environment:
      PACKAGE_ROOT: /home/ubuntu/cufflinks
      PLOTLY_CONFIG_DIR: ${HOME}/.plotly
      PLOTLY_PYTHON_VERSIONS: 2.7.8 3.4.1
      CORE_REQUIREMENTS_FILE: ${PACKAGE_ROOT}/requirements.txt
    
    steps:
      - run: 
          name: setup
          command: 
            bash .circleci/setup.sh
      - run:
          name: nose coverage
          command: pip install nose coverage
      # - run: bash setup.sh
      - run: cd ~ && python -c "import plotly"
      # _ save_cache:
        # - paths : ~/.pyenv/versions
      - run:
          name: running tests
          command: bash .circleci/test.sh
# dependencies:
#   override: 

    # run all the pre-written installers (this will take a *while*)
    # - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    # - tar xvzf ta-lib-0.4.0-src.tar.gz
    # - cd ta-lib && ./configure --prefix=/usr
    # - cd ta-lib && make
    # - cd ta-lib && sudo make install
    

    # install testing tools for circle's version of things
    # - pip install nose coverage
    # - pip install -I .

    # we need to cd out of the project root to ensure the install worked
    # - cd ~ && python -c "import plotly"

#   cache_directories:
#     - "~/.pyenv/versions"  # attempt to just cache installed pyenv things
#     # - "ta-lib"

# test:
#   override:

#     # run test suite in all our python versions
#     - bash test.sh
